REPOSITORY := erwinnttdata
NAME := phpmyadmin
VERSION ?= 4.6.2-fpm-build_007

build: _build ##@targets Builds the docker image.

clean: _clean ##@targets Removes the local docker image.

deploy: _deploy ##@targets Deployes the docker image to the repository.

include ../make_utils/Makefile.help
include ../make_utils/Makefile.functions
include ../make_utils/Makefile.image
