REPOSITORY := erwinnttdata
NAME := mysql
VERSION ?= 5.7-build_010

build: _build ##@targets Builds the docker image.

deploy: _deploy ##@targets Deployes the docker image to the repository.

include ../make_utils/Makefile.help
include ../make_utils/Makefile.functions
include ../make_utils/Makefile.image
